### ISSUE TITLE
Any idea why the audit tool doesn't show all my OBJKTs? Wanted to run a full audit 🤔 Not sure how it's supposed to work tho

### ISSUE THREAD

**Issue by flygohr** [atomantic/hicetnunc_tools#1]

**Comment by atomantic** [comment]
It looks like the BCD api isn't returning items that have never been listed yet. Try this tool for now and I'll look into another API: https://hicetnunc.miketyka.com/audit/

**Comment by atomantic** [comment]
Mike's has a number of additional features: burned, items in your collection that you didn't create, whether it's on the secondary market. I may just deprecate this CLI version in favor of his :)

**Comment by flygohr** [comment]
Thanks for the helpful answer 🙏🏻
