### ISSUE TITLE
IPFS API Version Mismatch

### ISSUE THREAD

**Issue by unityofmulti** [atomantic/hicetnunc_tools#2]
While trying to use pin.js to locally pin my collection, I only get this warning:

"api version mismatch (/go-ipfs/0.8.0/ != /go-ipfs/0.4.11-rc1/)"

Any chance to update the script, so that it will work with the latest IPFS API?

**Comment by atomantic** [comment]
This script just invokes the local ipfs CLI. I think what you are experiencing indicates you have two versions of ipfs installed, one running daemon using one version and an installed CLI using a different version. So if you were to run "which ipfs" that will point you to your CLI installation. Try removing or upgrading that version.

I've found that if you install ipfs desktop, it will also enable the CLI so you can get a running daemon and a CLI that match easily that way.

**Comment by unityofmulti** [comment]
Thanks for the fast reply. Updating my CLI installation and running IPFS desktop at the same time solved the issue for me.
