### ISSUE TITLE
error when pinning 

### ISSUE THREAD

**Issue by originaltomato** [atomantic/hicetnunc_tools#3]
`UnhandledPromiseRejectionWarning: SyntaxError: Unexpected token ] in JSON at position 12938
    at JSON.parse (<anonymous>)
    at IncomingMessage.<anonymous> (C:\repos\hen pin\hicetnunc_tools-main\lib\fetch.json.js:43:24)
    at IncomingMessage.emit (events.js:388:22)
    at endReadableNT (internal/streams/readable.js:1336:12)
    at processTicksAndRejections (internal/process/task_queues.js:82:21)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:22224) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:22224) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit cod`

**Comment by MAKIO135** [comment]
same error

**Comment by atomantic** [comment]
new repo: https://github.com/atomantic/henpin
