### ISSUE TITLE
TypeError: Cannot read property 'replace' of undefined

### ISSUE THREAD

**Issue by burnzzz** [atomantic/hicetnunc_tools#4]
System: Ubuntu 20.04
nodejs: v16.1.0
npm: v7.13.0

When trying to sync a full HEN node with `node henode.js` I always get:

`(node:107264) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'replace' of undefined
    at getNextPage (/home/museumstechnik/hicetnunc_tools/henode.js:163:27)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:107264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:107264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.`

Any ideas?

**Comment by atomantic** [comment]
Can you drop in the log data leading up to this. Curious where the offset range is looking. It appears to be an invalid token metadata that I'm not accounting for.

**Comment by atomantic** [comment]
Just pushed an update in the latest version that will account for it and log the chunk of the object it's seeing. Curious what you get in your logs when you run it.

**Comment by burnzzz** [comment]
Looks like you fixed it. After your update the sync is now running without hickups for a while now ...

> Running HENode in full cache mode
resuming HENode with offset 4740 (3079 cached already) 
3079 pinned items. Fetched offset=4740 with 10 tokens: 85155 - 85163
3079 pinned items. Fetched offset=4750 with 10 tokens: 85142 - 85153
3079 pinned items. Fetched offset=4760 with 10 tokens: 85134 - 85143
3079 pinned items. Fetched offset=4770 with 10 tokens: 85124 - 85132
3079 pinned items. Fetched offset=4780 with 10 tokens: 85115 - 85123
3079 pinned items. Fetched offset=4790 with 10 tokens: 85101 - 85116
3079 pinned items. Fetched offset=4800 with 10 tokens: 85095 - 85102
3079 pinned items. Fetched offset=4810 with 10 tokens: 85084 - 85093
3079 pinned items. Fetched offset=4820 with 10 tokens: 85075 - 85085
3079 pinned items. Fetched offset=4830 with 10 tokens: 85065 - 85073
3079 pinned items. Fetched offset=4840 with 10 tokens: 85055 - 85063
3079 pinned items. Fetched offset=4850 with 10 tokens: 85047 - 85054
3079 pinned items. Fetched offset=4860 with 10 tokens: 85035 - 85044
3079 pinned items. Fetched offset=4870 with 10 tokens: 85026 - 85036
3079 pinned items. Fetched offset=4880 with 10 tokens: 85015 - 85022
3079 pinned items. Fetched offset=4890 with 10 tokens: 85006 - 85016
3079 pinned items. Fetched offset=4900 with 10 tokens: 84996 - 85005
ensuring blocked token is not pinned: 85004
ensuring blocked token is not pinned: 84999
3079 pinned items. Fetched offset=4910 with 10 tokens: 84984 - 84997
ensuring blocked token is not pinned: 84988
ensuring blocked token is not pinned: 84984
3079 pinned items. Fetched offset=4920 with 10 tokens: 84973 - 84985
3079 pinned items. Fetched offset=4930 with 10 tokens: 84968 - 84974
3079 pinned items. Fetched offset=4940 with 10 tokens: 84957 - 84963
3079 pinned items. Fetched offset=4950 with 10 tokens: 84944 - 84958
3079 pinned items. Fetched offset=4960 with 10 tokens: 84936 - 84945
3079 pinned items. Fetched offset=4970 with 10 tokens: 84927 - 84938
3079 pinned items. Fetched offset=4980 with 10 tokens: 84917 - 84928
3079 pinned items. Fetched offset=4990 with 10 tokens: 84908 - 84918
3079 pinned items. Fetched offset=5000 with 10 tokens: 84900 - 84906
ensuring blocked token is not pinned: 84897
3079 pinned items. Fetched offset=5010 with 10 tokens: 84888 - 84901
3079 pinned items. Fetched offset=5020 with 10 tokens: 84876 - 84887
3079 pinned items. Fetched offset=5030 with 10 tokens: 84869 - 84877
3079 pinned items. Fetched offset=5040 with 10 tokens: 84857 - 84866
3079 pinned items. Fetched offset=5050 with 10 tokens: 84848 - 84858
3079 pinned items. Fetched offset=5060 with 10 tokens: 84838 - 84849
3079 pinned items. Fetched offset=5070 with 10 tokens: 84827 - 84838
3079 pinned items. Fetched offset=5080 with 10 tokens: 84824 - 84830
3079 pinned items. Fetched offset=5090 with 10 tokens: 84811 - 84819
3079 pinned items. Fetched offset=5100 with 10 tokens: 84799 - 84812
3079 pinned items. Fetched offset=5110 with 10 tokens: 84792 - 84800
3079 pinned items. Fetched offset=5120 with 10 tokens: 84782 - 84789
3079 pinned items. Fetched offset=5130 with 10 tokens: 84771 - 84780
3079 pinned items. Fetched offset=5140 with 10 tokens: 84764 - 84769
3079 pinned items. Fetched offset=5150 with 10 tokens: 84751 - 84759
3079 pinned items. Fetched offset=5160 with 10 tokens: 84741 - 84752
3079 pinned items. Fetched offset=5170 with 10 tokens: 84728 - 84739
3079 pinned items. Fetched offset=5180 with 10 tokens: 84721 - 84729
3079 pinned items. Fetched offset=5190 with 10 tokens: 84715 - 84723
3079 pinned items. Fetched offset=5200 with 10 tokens: 84704 - 84716
3079 pinned items. Fetched offset=5210 with 10 tokens: 84694 - 84705
3079 pinned items. Fetched offset=5220 with 10 tokens: 84686 - 84695
3079 pinned items. Fetched offset=5230 with 10 tokens: 84677 - 84684
3079 pinned items. Fetched offset=5240 with 10 tokens: 84663 - 84678
3079 pinned items. Fetched offset=5250 with 10 tokens: 84653 - 84664
3079 pinned items. Fetched offset=5260 with 10 tokens: 84647 - 84654
3079 pinned items. Fetched offset=5270 with 10 tokens: 84633 - 84644
3079 pinned items. Fetched offset=5280 with 10 tokens: 84626 - 84634
3079 pinned items. Fetched offset=5290 with 10 tokens: 84619 - 84628
3079 pinned items. Fetched offset=5300 with 10 tokens: 84611 - 84618
✅ token:84615-content	 pinned QmWw5yYY4PVhu4ja9fVgKb8znkTzpsTqE3R9TDLVeeARXY recursively
✅ token:84615-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84615-meta	 pinned QmQPLqMhrjfQauHg3SLzuWBK5auekqVwXbjU8TF4jLtuuZ recursively
token does not appear to have a metadata block { prompt: 'First Day Of The Monsters. blender eevee RTX on' }
✅ token:84614-content	 pinned QmbN2oMyGKbMYK1p1r8NcyaVkPsKSudBDNm543cQpz8v7A recursively
✅ token:84614-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84614-meta	 pinned QmVSQcMKSczoFFszTErf8bKcUYPRMtjzGwv71XEAfkNAyp recursively
✅ token:84612-content	 pinned QmZihoZymoZHumLTgNPNhSkY12X8JxprkNUek6xggNr9wd recursively
✅ token:84612-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84612-meta	 pinned Qmf2jiWsTx3trgBFg7fcL3e6fXsoCthwNQXQcRSCWGce9m recursively
✅ token:84609-content	 pinned QmdAzHgj4sgoWt33hqrTVaKq86Gb5S57DUFRWRawkYF1aq recursively
✅ token:84609-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84609-meta	 pinned QmRUguzzwhkjgFHHiSCT2xsCrmZRNRSLcB5FM4dj8Y5YfH recursively
✅ token:84610-content	 pinned QmenVrvhYixWqs4UsBJqgTdKTWr8L1xqK2NsTaoj76MMAz recursively
✅ token:84610-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84610-meta	 pinned QmY8qGsxRLK9Mece9MTYjsHsgg8jByvBAvy67XKmaVL6bA recursively
✅ token:84611-content	 pinned QmYkYmoGi45W6ZJD9GjCKiZEctS33L99DMMvjc9CXfDiwZ recursively
✅ token:84611-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84611-meta	 pinned Qmd4A6mQdpAW5fV1hBJjUPEEMN8d29rDjXadzRUc3BDoDM recursively
3085 pinned items. Fetched offset=5310 with 10 tokens: 84602 - 84609
✅ token:84606-content	 pinned QmRPzY8KVhx9gDkzevH9rmjhpfWfpsvpsUxr7nNHNUi4M5 recursively
✅ token:84606-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84606-meta	 pinned QmT5pSHtrTCcevRmbiz9S1WttLiUGLCAWEui9M5VCcCcnt recursively
✅ token:84607-content	 pinned QmefzYjvphu99HJ7CkoUie3MC9JMyZeEnqd63f1qD6TvmT recursively
✅ token:84607-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84607-meta	 pinned QmQasn8KtTHRTpmLAfDJALXnhh4VbVShsqLKYrs8vDnCkx recursively
✅ token:84608-content	 pinned QmTgW5t1a3MYiWgVsDyeK73PuerdWA2APsqsBtQ2np2Jbd recursively
✅ token:84608-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84608-meta	 pinned QmbTNPdLN2oPzLybh4DjHpRJ3BjdWAnTHWroEuEvsoxoJo recursively
✅ token:84605-content	 pinned QmdJdpJ7fr9aTx7NFUaFEwv1FvavXZz4hsiiyQNH33VYAQ recursively
✅ token:84605-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84605-meta	 pinned QmSH8bBp52zPAdsjcvTrwGqfYkME2gHbior3uAqXA5cdec recursively
✅ token:84604-content	 pinned QmV1devdZMeKWs941TSDfQ1SyMVMYUW9NN7XqFDRL5bNWP recursively
✅ token:84604-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84604-meta	 pinned QmaEU1BqVdTAimfDtLZN1rnXvSvfSyQhoKaxdVSBmDdmAS recursively
✅ token:84603-content	 pinned QmfFtHUAD1eVBFQCJnLYeHchoeBEVULaCK9iWHqsbZpFJX recursively
✅ token:84603-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84603-meta	 pinned QmZsY5G9TnACY23Ppbgk7Vw6bQXhe1x5yFSU1SG6Q3qXoL recursively
✅ token:84602-content	 pinned QmUHHRgSe4hjmFDAtXDzpcYSh3dPbNhmAGhVgGQKFcnajN recursively
✅ token:84602-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84602-meta	 pinned QmZ1cAdNvuXMGxdC1pdUg9Ginzp91xDntjf3Qx67dXK6Km recursively
3092 pinned items. Fetched offset=5320 with 10 tokens: 84592 - 84601
✅ token:84601-content	 pinned QmYTQuTP1hd3AhbyT8W5ynSpWLYG1dUEpS7yav5RbC8viz recursively
✅ token:84601-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84601-meta	 pinned QmSgc9fQ3CHmxAjxj8PsNsBX58TywZwYNQv46EczfnwQ7A recursively
✅ token:84599-content	 pinned QmQnd7LLZ6jNt3FQXLizdqufuAArzRQif3LBSrh27ZMpaa recursively
✅ token:84599-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84599-meta	 pinned QmZn4cAF7CyrjHuy68UMvWVNmc4qnxEGuzMtp6mKQE8q1e recursively
✅ token:84600-content	 pinned QmV1xzB6qCRobWTfbfUxvvLBtFgpwBRcaG338cmG9Gff1Q recursively
✅ token:84600-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84600-meta	 pinned QmeKYjhTpLTM1osSndWJssZr21jdSfGByS2z9zv7vqhe9Q recursively
✅ token:84596-content	 pinned QmPLzcCpEN1W3rkBQ3v9VxVaGTpKoVaCgbR5MqeZCvctMK recursively
✅ token:84596-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84596-meta	 pinned QmZntGdFd1qB98sQVqVDi6dAJ2t675CuW6Pj6axHqr6cuf recursively
✅ token:84597-content	 pinned QmdUvjnCGXnnpEhyyVyLEX5vP19X9dAr15qy7jj7kPRTET recursively
✅ token:84597-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84597-meta	 pinned QmebfNrEUdeEDZcdfueEDZqhFGqCb8S1kv2NrvC6oC9ufL recursively
✅ token:84598-content	 pinned QmQ8NfyJuAYThSkUAwKasGvm1P3epNk2tTp9hGUBHJ5gAt recursively
✅ token:84598-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84598-meta	 pinned Qmd9bVwgDNtTqgRE6fThqzVBvNgucVoNrdEkFo95ybgC1T recursively
✅ token:84595-content	 pinned Qmd4zp4krpPXsLfvi5ULeK9AG35yanNE2ppJEWajF6G7nL recursively
✅ token:84595-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84595-meta	 pinned QmcywWvZWztYHrkYNSYrmLtoWDKDucixKPWGM8CxLwzvaz recursively
✅ token:84594-content	 pinned QmS2SnkfJQJXU4FAz6jc2sC2VkkqfytiLQohPxevYXj414 recursively
✅ token:84594-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84594-meta	 pinned Qmb3vYdMBUZfpS9Bwhiihu4mQWZ2q9dNiz9XJaZ3M5cGLs recursively
✅ token:84591-content	 pinned QmPgCnQE7ykQ4FYA8SePLG1UAHV3zyt6WYzTg4VdHyzTAF recursively
✅ token:84591-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84591-meta	 pinned Qmbm9b8jnXbFx858iGarA5LZ9Ekw8EuQ2Zb4qgRBNjZjD6 recursively
✅ token:84592-content	 pinned QmVtbfw8U5AwfoGrnJ4UbDAPdFBvL9DDpKGJjN36C94tyC recursively
✅ token:84592-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84592-meta	 pinned QmR7d1BiDxkv9HNHGHJLu5qnXx4xjwPENubrj7mZW9xQJ8 recursively
3102 pinned items. Fetched offset=5330 with 10 tokens: 84582 - 84593
✅ token:84593-content	 pinned QmbWQhtmJo3xYVqUv25kfopBuFXDTeuf6mXozd4KuvQsQs recursively
✅ token:84593-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84593-meta	 pinned QmWfKYxtfeEhxYg84GcsnUxEmkQqEdfkzR1dN9WmwcnySE recursively
✅ token:84590-content	 pinned QmT1UgnVd1g6WvnUSPpctBYXWDAtwbzhKyH38NPMoS4T6G recursively
✅ token:84590-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84590-meta	 pinned QmdVZVC5aGB3qgWj1CfLMoH4xnSzUiyzG8v6mcQr1aqVmc recursively
✅ token:84589-content	 pinned Qme5njNEtSTVDpHtrTw8HEACm3KNQiieTmUx3XMU5w22sh recursively
✅ token:84589-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84589-meta	 pinned QmfYbBYJM31CQbHNea3s5PExoAGWRPHEJaGWeJhN8Ki61Z recursively
✅ token:84587-content	 pinned QmcynowmfSarQ1KySQFtXnpygrVnv9jwfUmcdse9UenQMh recursively
✅ token:84587-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84587-meta	 pinned QmZ8fJhXiGpb44VwA4PpUQArEGu4LXWXPtibx2dGkmBaT9 recursively
✅ token:84588-content	 pinned Qmf78y9qcnzUSLoLnNybuhNdg2XzoLNwEUagWhyGzTzzqR recursively
✅ token:84588-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84588-meta	 pinned QmedaVKc25mAK5FySbqxAYEHmBbmnxYjqtSWPyjSo4uDZU recursively
✅ token:84586-content	 pinned QmTgW5t1a3MYiWgVsDyeK73PuerdWA2APsqsBtQ2np2Jbd recursively
✅ token:84586-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84586-meta	 pinned QmWATiPEUDnXeDwuQfHsAjqa1bLWt9yimecE5bFXLQc4iu recursively
✅ token:84584-content	 pinned QmcZ5ffe2769FKydhQamn9wyfHkHtKWbZ8tyQ9JjhLVzrq recursively
✅ token:84584-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84584-meta	 pinned QmZ9gHiUGp4RGefG7qG3WWHrc9uxBMVmeUGZ7HvftMbCSH recursively
✅ token:84585-content	 pinned QmbsjJTFiE6sX8bymemjrtoL8CUv9SuvhcxSP9SAYCPJDM recursively
✅ token:84585-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84585-meta	 pinned QmYFBtpTooCgZkDb2YoeTXhktgzkWLsKnoAwins2Hb84ky recursively
✅ token:84583-content	 pinned QmQQDjp2nWaW8VTZSgcsCRGa6YsYwrntheHZz4uv1VgMHC recursively
✅ token:84583-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84583-meta	 pinned QmadeCFvLdeh89GxANc1qrypFUUPmoaGyuiW3T6eBYppiC recursively
✅ token:84582-content	 pinned QmZh9ahYf5Mi9gX4RJuVRY5P6u6WvHG9gH6Fu8pALnNmpU recursively
✅ token:84582-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84582-meta	 pinned QmURpikg7MhLwtNEkJt9tbQ8NQwk8HCNer6hQQWzCkdJY1 recursively
3112 pinned items. Fetched offset=5340 with 10 tokens: 84577 - 84586
✅ token:84580-content	 pinned QmRKcMP6nVHZqEguPVZens2FPNy5SETkcNcrtYD4bQ1FQ1 recursively
✅ token:84580-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84580-meta	 pinned QmZgEWjJbXQjFi4oMAuM5zSSBMjVB8gxfNH9DCSt7QUtKB recursively
✅ token:84581-content	 pinned QmYMRNjZRG5QvPQ1NLDDEU3ZtXdZ4WC7KTAdWhLUTU1J9A recursively
✅ token:84581-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84581-meta	 pinned Qmdx2VxfsG5EEbGjhvVpnPAxktsgm2pfnnFx8Jzz7pvEs7 recursively
✅ token:84579-content	 pinned QmWKHHC4aJtZPtekMpVAHoyfMo21qjvK3j81ER2W8igSzU recursively
✅ token:84579-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84579-meta	 pinned QmR2vgWtFX1zmAWcXGKo6y5zhNkZnaxKewGyRiWLiwafM6 recursively
✅ token:84578-content	 pinned QmSotLio4vnNXw1TGPHjeoGJYmKGekykr1asrai5rejHGm recursively
✅ token:84578-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84578-meta	 pinned QmdFvFM86bxoHPz8T3WeJ23ayV53rTp2XxqLh1xjbqLe2o recursively
✅ token:84577-content	 pinned QmTP9dCVDDarfsN2NE4h9uZeveXWNfwgowmGQsa6TkA1sc recursively
✅ token:84577-thumb	 pinned QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc recursively
✅ token:84577-meta	 pinned QmZGj3psE3Wf2nVxQavpMDu5nt5RsqkfhYGbu7Ve8AJAgT recursively

**Comment by atomantic** [comment]
Thanks! That helps a lot. I just pushed another fix that will allow that token to be pinned: https://www.hicetnunc.xyz/objkt/84613 --it looks like something changed with the underlying API and now creators is a top level field in the token data so I don't need to fetch the token info anymore. This should speed up henode.js a little bit too and require fewer API calls :)

**Comment by atomantic** [comment]
If you want to make sure you get that token in your pin set, you can backup your pointer by adjusting the `offset` field in your `.cache.json` file to `5330` and restart henode.js :)

**Comment by atomantic** [comment]
or you can manually pin it with `node pin.js tz1PTiGJ674i1feGXvmH3a61uXjf8z8Tp3Et` to ensure you have that creator's works all pinned.

**Comment by burnzzz** [comment]
Applied the update an it works without problems and really seems to be faster now. Thx for the fix! Great work!
