### ISSUE TITLE
/bin/sh: ipfs: command not found

### ISSUE THREAD

**Issue by makeitrad** [atomantic/hicetnunc_tools#5]
Hello when running pin.js UI get the following error.

🚨 error with QmNrhZHUaEqxhyLfqoq1mtHSipkWHeT31LNHb1QEbDHgnc /bin/sh: ipfs: command not found

it happens for all 500 items in my wallet.

I am on Mac OS 11.4
Desktop IPFS is running with no errors
AGENT go-ipfs v0.8.0
UI v2.12.3

NODE v14.17.1

and the latest hicetnuc_tools from github. 

Seems like sh cant find the path to the desktop IPFS app. Can I set this variable somewhere in the OS or hicetnuc tools?

**Comment by atomantic** [comment]
when you installed ipfs desktop, did you restart your terminal? It should install the CLI tool as well and add it to your path. Try launching a new terminal, then try reinstalling IPFS desktop and launch a new terminal.

**Comment by makeitrad** [comment]
I had to install desktop and install via homebrew. Once I did this all worked well. Just will have to remember to update both when updating. Thanks for helping.
