### ISSUE TITLE
Is it normal that the program just hangs when trying to pin the same content?

### ISSUE THREAD

**Issue by flygohr** [atomantic/hicetnunc_tools#6]
![image](https://user-images.githubusercontent.com/13753044/123780794-dcdb7100-d8d3-11eb-81df-1383e902326b.png)

Third time I run the program and it just hangs there

**Comment by atomantic** [comment]
yeah, that can happen with IPFS trying to resolve the items. I've got a new repo for pinning here: https://github.com/atomantic/henpin

Sometimes IPFS takes a while to resolve a path to the file though...
