### ISSUE TITLE
"Error: Failed to load page, status code: 500"

### ISSUE THREAD

**Issue by peterkaminski** [atomantic/hicetnunc_tools#7]
Thank you for creating these tools. :-)

When I try to run `pin.js`, the script stops with "Error: Failed to load page, status code: 500".

With `--trace-warnings` on, it looks like it is the AWS API Gateway address for the HEN API that is returning the HTTP 500 error:

```
> node --trace-warnings pin.js tz1XHADaUcMSkTN9gdmtRqcnrrZfs4tNkCPg
⚡ fetching content for address tz1XHADaUcMSkTN9gdmtRqcnrrZfs4tNkCPg
500 {
  hostname: '51rknuvw76.execute-api.us-east-1.amazonaws.com',
  port: 443,
  path: '/dev/tz',
  method: 'POST',
  headers: { 'Content-Type': 'application/json', 'Content-Length': 45 },
  body: { tz: 'tz1XHADaUcMSkTN9gdmtRqcnrrZfs4tNkCPg' }
}
(node:9515) UnhandledPromiseRejectionWarning: Error: Failed to load page, status code: 500
    at ClientRequest.<anonymous> (/Users/peterkaminski/src/atomantic/hicetnunc_tools/lib/fetch.json.js:33:11)
```

I note there is a [comment in lib/get.tz.js](https://github.com/atomantic/hicetnunc_tools/blob/c2afd9b16a67c9686a5d12f08e6b72e7a2d21992/lib/get.tz.js#L2) that refers to the code that hits `https://51rknuvw76.execute-api.us-east-1.amazonaws.com/dev/tz`:

```
 * fetch collected tz info from hicetnunc API
 * NOTE: someday this might stop working
```

My environment:

- macOS Big Sur Version 11.5.2 (20G95)
- node v14.15.3
- npm 7.10.0
- IPFS Desktop Version 0.16.3
- `node pin.conseil.js tz1iyFi4WjSttoja7Vi1EJYMEKKSebQyMkF9` ran and pinned many things and seemed to complete okay

**Comment by MAKIO135** [comment]
same issue

**Comment by atomantic** [comment]
killing this repo in favor of a new one that uses hicdex :)

https://github.com/atomantic/henpin
